name: Build Armbian

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Checkout support scripts
        uses: actions/checkout@v3.1.0
        with:
          repository: armbian/scripts
          path: scripts
          clean: false
      - name: Checkout build
        uses: actions/checkout@v3.1.0
        with:
          repository: armbian/build
          path: build
          clean: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: prepare patches
        run: cp -a userpatches build/userpatches
      - name: prepare configs
        run: cp scripts/configs/* build/userpatches/
      # stolen from official arm repo
      - name: patch docker build for non-interactive
        run: sed -i "s/-it --rm/-i --rm/" build/userpatches/config-docker.conf
      - name: build image
        run: (cd build && ./compile.sh docker BOARD=khadas-vim3 BRANCH=current RELEASE=jammy BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img)
      - name: "release"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/output/images/*"
          tag: "${{ env.VERSION }}"
          omitBody: true
          omitName: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
